--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,7 +5,7 @@
   build:
     strategy:
       matrix:
-        go-version: [~1.18, ^1]
+        go-version: ['~1.18', '^1']
         os: [ubuntu-latest, macos-latest, windows-latest]
     runs-on: ${{ matrix.os }}
     env:
@@ -44,4 +44,4 @@
         run: |
           go mod tidy
           go build -v ./...
-        working-directory: ./tutorials
+        working-directory: ./tutorials